name: my_env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - gdal
  - opencv
  - boost
  - pybind11
  - compilers
  - pillow
  - rasterio
  - pyproj
  - tqdm
  - pytorch==1.8
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7