name: my_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.8
  - conda-forge::gdal
  - conda-forge::opencv
  - pillow
  - rasterio
  - pyproj
  - tqdm
  - ftfy
  - regex
  - pytorch::pytorch==1.12.1 
  - pytorch::torchvision==0.13.1 
  - pytorch::torchaudio==0.12.1 
  - pytorch::cudatoolkit=11.3
