name: my_env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.8
  - gdal
  - opencv
  - boost
  - pybind11
  - compilers
  - pillow
  - rasterio
  - pyproj
  - tqdm
  - pytorch==1.12.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3