package:
  name: my_project
  version: 1.0.0

source:
  path: .

build:
  number: 0
  script: "python setup.py install"  # or similar

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - boost
    - gdal
    - opencv

about:
  home: "https://github.com/lubyant/ShorelineCalculator"
  license: "MIT"
  summary: "A brief description of my project."

