[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shoreline_calculator"
version = "0.0.1"
authors = [
  { name="Boyuan Lu", email="blu38@wisc.edu" },
  { name="Wei Wang", email="wwang487@wisc.edu" },
]
description = "A package for caluclating shoreline erosion"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
Homepage = "https://github.com/lubyant/ShorelineCalculator"
Issues = "https://github.com/lubyant/ShorelineCalculator/issues"

[tool.setuptools]
package-dir = {"" = "shorelinecalculator"}