# opencv
find_package(OpenCV CONFIG REQUIRED)
include_directories( ${OpenCV_INCLUDE_DIRS} )
# gdal
find_package(GDAL CONFIG REQUIRED)
# find_path(GDAL_INCLUDE_DIR gdal.h PATH_SUFFIXES gdal)
# find_library(GDAL_LIBRARY NAMES gdal)
# include(FindPackageHandleStandardArgs)
# find_package_handle_standard_args(GDAL DEFAULT_MSG GDAL_LIBRARY GDAL_INCLUDE_DIR)
# if(GDAL_FOUND)
#     set(GDAL_INCLUDE_DIRS ${GDAL_INCLUDE_DIR})
#     set(GDAL_LIBRARIES ${GDAL_LIBRARY})
# else()
#     message(FATAL_ERROR "GDAL not found!")
# endif()
# include_directories(${GDAL_INCLUDE_DIRS})

add_library(DSAS STATIC geometry.cpp image.cpp shorelinecalculator.cpp utility.cpp)
target_link_libraries(DSAS PRIVATE pthread)
target_link_libraries(DSAS PRIVATE ${OpenCV_LIBS})
target_link_libraries(DSAS PRIVATE GDAL::GDAL)
