name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.9
        activate-environment: my_env
        environment-file: environment.yml
        auto-activate-base: false

    - name: Manually activate Conda environment and check CONDA_PREFIX
      shell: bash -l {0}
      run: |
        conda activate my_env
        echo "CONDA_PREFIX=$CONDA_PREFIX"

    - name: Build and Install Module
      run: |
        echo "CONDA_PREFIX=$CONDA_PREFIX"

    - name: Run Tests
      run: |
        python -m unittest discover tests
